version: "3.8"
services:
  test:
    build:
      context: .
      dockerfile: docker/DockerFile_test
    profiles: [ "test" ]
    container_name: app-business-logic-tests
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./tests:/tests
    command: sh -c "pytest /tests -k 'test' -vv --cache-clear --show-capture=no -r chars"

    depends_on:
      - timescaledb
  timescaledb:
    extends:
      file: ../my-power-base.yaml
      service: app
  app:
    extends:
      file: ../my-power-base.yaml
      service: timescaledb
    depends_on:
      - timescaledb
