services:
    mqtt:
      container_name: mqtt
      image: eclipse-mosquitto:2.0.18
      restart: unless-stopped
      volumes:
        - "./mosquitto-data:/mosquitto"
      ports:
        - "1883:1883"
        - "9001:9001"
      command: "mosquitto -c /mosquitto-no-auth.conf"
    energy-agent:
      build:
        context: .
        dockerfile: docker/Dockerfile
      container_name: energy-agent
      depends_on:
          - mqtt
      environment:
        CONFIG_PATH: "/data"
        RDDL_TOPIC: "rddl/SMD/#"
        TRUST_WALLET_PORT: "/dev/ttyACM0"
        NOTARIZE_INTERVAL: 1
        CLIENT_ID: "energy_agent"
        PORT: 2138
      ports:
        - 2138:2138
      privileged: true
      volumes:
        - ./energy-agent-data:/data
      restart: always
      network_mode: "host"  # Share host network
      cap_add:
        - NET_RAW  # Add raw socket capability