version: "3.8"
services:
    mqtt:
        image: eclipse-mosquitto:2.0.10
        container_name: mqtt
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        restart: always
    energy-agent:
        build:
          context: .
          dockerfile: docker/Dockerfile
        container_name: energy-agent
        depends_on:
            - mqtt
        environment:
            - MQTT_HOST=mqtt
            - MQTT_PORT=1883
            - MQTT_TOPIC=energy
        restart: always