version: "3.8"
services:
    mqtt:
        image: eclipse-mosquitto:2.0.10
        container_name: mqtt
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        restart: always
    energy-agent:
        build:
          context: .
          dockerfile: docker/Dockerfile
        container_name: energy-agent
        depends_on:
            - mqtt
        environment:
            CONFIG_PATH: "/data/config"
            RDDL_TOPIC: "/rddl/SMD/"
            TRUST_WALLET_PORT: "/dev/ttyACM0"
            LIBOCC_PATH: "lib/linux/armv7/libocc.so"
            NOTARIZE_INTERVAL: 60
            CLIENT_ID: "energy_agent"
        privileged: true
        volumes:
            -   ./data:/data
        restart: always