version: "3.8"
services:
  timescaledb:
    extends:
      file: ./my-power-base.yaml
      service: timescaledb
  app:
    extends:
      file: ./my-power-base.yaml
      service: app
    depends_on:
      - timescaledb
  test:
    build:
      context: .
      dockerfile: docker/DockerFile
    profiles: [ "test" ]
    container_name: rddl-energy-agent-tests
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./tests:/tests
    command: sh -c "pytest /tests -k 'test' -vv "
#    depends_on:
#      - timescaledb
