services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.18
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
  energy-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: energy-agent
    depends_on:
      - mqtt
    environment:
      CONFIG_PATH: "/data"
      SMD_TOPIC: "rddl/SMD/#"
      TRUST_WALLET_PORT: "/dev/ttyACM0"
      NOTARIZE_INTERVAL: 60
      RDDL_NETWORK_MODE: testnet
      PORT: 2138
      LOG_LEVEL: DEBUG
      LOG_FILE_PATH: "/data/log/energy_agent.log"
    ports:
      - 2138:2138
    privileged: true
    volumes:
      - ./app:/app
      - ./energy-agent-data:/data
    restart: always
    network_mode: "host"
    cap_add:
      - NET_RAW