version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    profiles: [ "app" ]
    container_name: timescaledb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: docker/DockerFile
    profiles: [ "app" ]
    container_name: app-business-logic
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --timeout-keep-alive 240 --reload"