version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/DockerFile_Pip
    profiles: [ "app" ]
    container_name: rddl-energy-agent
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    command: python -m main
    networks:
      - my-network

networks:
  my-network:
    external:
      name: builder-space_default