[tool.poetry]
name = "rddl-energy-agent"
version = "0.1.0"
description = ""
authors = ["Cybnon <stefan.weber93@googlemail.com>"]
readme = "README.md"
packages = [{include = "rddl-energy-agent"}]

[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.2"
pycryptodome = "^3.20"
pydantic = "^2.7.0"
gurux-dlms = "^1.0.150"
lxml = "^5.2.1"
cryptography = "^42.0.5"
paho-mqtt = "^2.0.0"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"
setuptools = "^69.5.1"
jinja2 = "^3.1.3"
python-multipart = "^0.0.9"
ipfs-cid = "^1.0.0"
osc4py3 = "^1.0.8"

[tool.poetry.dev-dependencies]
pytest = "^8.1.1"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.23.6"
black = "24.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
