[tool.poetry]
name = "business-logic"
version = "0.1.0"
description = ""
authors = ["Cybnon <stefan.weber93@googlemail.com>"]
readme = "README.md"
packages = [{include = "app-business-logic"}]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
grpcio = "^1.53.0"
grpcio-tools = "^1.53.0"
ecdsa = "^0.18.0"
pycryptodome = "^3.17"
pydantic = "^1.10.7"
gurux-dlms = "^1.0.144"
lxml = "^4.9.2"
cryptography = "^42.0.4"
paho-mqtt = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
pytest-mock = "^3.10.0"
pytest-asyncio = "^0.20.3"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
