FROM python:3.10-alpine

RUN apk update && apk upgrade

RUN apk add -U \
    build-base \
    curl \
    eudev-dev \
    git \
    libffi-dev \
    libusb-dev \
    openssh \
    openssl-dev \
    protobuf-dev \
    udev \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    cargo \
    pkgconfig

COPY . .
COPY poetry.lock pyproject.toml ./

RUN pip install --only-binary cryptography poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-root --only main

EXPOSE 8080:8080

CMD ["python", "-m", "main"]
