FROM python:3.10-alpine

RUN apk update && apk upgrade

RUN apk add -U \
    build-base \
    curl \
    eudev-dev \
    git \
    libffi-dev \
    libusb-dev \
    openssh \
    openssl-dev \
    protobuf-dev \
    udev

WORKDIR /app


COPY .  .
COPY poetry.lock pyproject.toml ./

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-root

# The ENTRYPOINT is set to use the Typer script
ENTRYPOINT ["python", "main_typer.py"]

# Replace "your_typer_command" with the Typer command you want to use
CMD ["fetch_data"]
