FROM python:3.9-slim

COPY app  /app
COPY tests /tests
COPY poetry.lock pyproject.toml ./

RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev --no-root

EXPOSE 8080:8080

CMD ["pytest", "/tests", "-k", "test", "-vv", "--cache-clear", "-r", "chars", "--log-level=DEBUG"]