# Stage 1: Build on a python:3.9 image
FROM python:3.9 as builder

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libffi-dev \
    libusb-1.0-0-dev \
    openssh-client \
    libssl-dev \
    protobuf-compiler \
    libudev-dev \
    gcc \
    libffi-dev \
    pkg-config \
    cargo \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the builder container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies in the builder container
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application into the container
COPY . .

# Stage 2: Copy necessary files to python:3.9-slim image
FROM python:3.9-slim

# Set the working directory in the final container
WORKDIR /app

# Copy the installed dependencies from the builder container
COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

# Copy the application from the builder container
COPY --from=builder /app/ .

# Ensure main.py is present
RUN ls -la

# Run the application
CMD ["python", "-m", "main"]
