FROM python:3.10-alpine

RUN apk update && apk upgrade

Run apk add -U \
    build-base \
    curl \
    eudev-dev \
    git \
    libffi-dev \
    libusb-dev \
    openssh \
    openssl-dev \
    protobuf-dev \
    udev

COPY . .
COPY poetry.lock pyproject.toml ./

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-root --only main

EXPOSE 8080:8080

CMD ["python", "-m", "main"]
