# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeterConnectorProto/meter_connector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)MeterConnectorProto/meter_connector.proto\x12\x13MeterConnectorProto\"\x0f\n\rSMDataRequest\"\x1e\n\x0bSMDataReply\x12\x0f\n\x07message\x18\x01 \x01(\t2e\n\x0eMeterConnector\x12S\n\treadMeter\x12\".MeterConnectorProto.SMDataRequest\x1a .MeterConnectorProto.SMDataReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MeterConnectorProto.meter_connector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SMDATAREQUEST._serialized_start=66
  _SMDATAREQUEST._serialized_end=81
  _SMDATAREPLY._serialized_start=83
  _SMDATAREPLY._serialized_end=113
  _METERCONNECTOR._serialized_start=115
  _METERCONNECTOR._serialized_end=216
# @@protoc_insertion_point(module_scope)
